---
#- name: Login to OpenShift
#  command: oc login -u admin -p Redhat1!

- name: Get current replicas
  command: "oc get dc myapp -n battle-royale"
  register: dc_out

#- name: Show stuff
#  debug:
#    msg: dc_out is {{ dc_out.stdout.split()[9] | int + 1 }}
#    verbosity: 0

- name: Scale up OpenShift
  command: oc scale --replicas="{{ dc_out.stdout.split()[9] | int + 1 }}" dc/myapp -n battle-royale

